# Generated by Django 5.0.6 on 2024-06-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_rest", "0002_usertasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroDeUsuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(default="", max_length=255)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
